services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: todo-postgres
      POSTGRES_USER: todo-postgres
      POSTGRES_PASSWORD: todo-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo
      SPRING_DATASOURCE_USERNAME: todo-postgres
      SPRING_DATASOURCE_PASSWORD: todo-postgres
    ports:
      - "8080:8080"
    # Uncomment if you want to wait for db to be ready
    # entrypoint: ["sh", "-c", "sleep 10 && java -jar app.jar"]

volumes:
  pgdata: