# To use this file:
#
#   % ln -s Makefile.example Makefile
RUN_ARGS := $(wordlist 2, $(words $(MAKECMDGOALS)), $(MAKECMDGOALS))

run:
	./mvnw spring-boot:run

all-tests:
	cd ./docker-test && docker-compose up --abort-on-container-exit --exit-code-from test-app

test-build:
	cd ./docker-test && docker-compose build

test-down:
	cd ./docker-test && docker-compose down